apiVersion: v1
kind: Service
metadata:
  name: testbbbbb
  namespace: default
  labels:
    app: testbbbbb
spec:
  type: ClusterIP
  selector:
    app: testbbbbb
  ports:
    - name: https
      protocol: TCP
      port: 5876
      targetPort: 5876

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbbbbb
  namespace: default
  labels:
    app: testbbbbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbbbbb
  template:
    metadata:
      labels:
        app: testbbbbb
    spec:
      containers:
        - name: testbbbbb-container
          image: satyamp07/n8n:latest
          ports:
            - containerPort: 5876
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env: []
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testbbbbb
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: n8n-n-wcz.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testbbbbb
                port:
                  number: 5876
  tls:
    - hosts:
        - n8n-n-wcz.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
