apiVersion: v1
kind: Service
metadata:
  name: testbefore
  namespace: dev
  labels:
    app: testbefore
spec:
  type: ClusterIP
  selector:
    app: testbefore
  ports:
    - name: https
      protocol: TCP
      port: 5876
      targetPort: 5876

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbefore
  namespace: dev
  labels:
    app: testbefore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbefore
  template:
    metadata:
      labels:
        app: testbefore
    spec:
      containers:
        - name: testbefore-container
          image: satyamp07/n8n:latest
          ports:
            - containerPort: 5876
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env: []
      imagePullSecrets:
        - name: scoutflo-satyam-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testbefore
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: n8n-crzvg.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testbefore
                port:
                  number: 5876
  tls:
    - hosts:
        - n8n-crzvg.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
